plugins {
    id 'org.jetbrains.kotlin.jvm'
}

group = 'cn.coostack.cooparticlesapi'
version = '2.1.2'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.0")
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}