import net.fabricmc.loom.task.RemapJarTask

plugins {
    id 'fabric-loom'
    id 'multiloader-loader'
    id 'org.jetbrains.kotlin.jvm'
}

tasks.javadoc {
    // fuck javadoc encode error
    enabled = false
}

configurations {
    embed
    implementation.extendsFrom(embed)
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
//    mappings loom.layered {
//        officialMojangMappings()
//        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
//    }
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
    embed fileTree(dir: "../depend", includes: ["*.jar"])
    embed 'io.github.classgraph:classgraph:4.8.184'
    modImplementation fileTree(dir: "../depend", includes: ["*.jar"])
    modImplementation 'io.github.classgraph:classgraph:4.8.184'
    modCompileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])

}

tasks.register("sourceWithCommon", Jar) {
    def current = tasks.named("sourcesJar").get()
    dependsOn(current)
    from current.outputs.files.collect { zipTree(it) }
    def other = project(":common").tasks.named("sourcesJar")
    dependsOn(other)
    from zipTree(other.get().archiveFile)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude "META-INT/**"
    destinationDirectory.set(file("../builds/sources"))
    archiveFileName = "${rootProject.mod_name}-Fabric-Source-${rootProject.version}.jar"
}
tasks.named("jar", Jar) {
    from(configurations.embed.collect {
        it.isDirectory() ? it : zipTree(it)
    }) {
        // 排除可能冲突的文件
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    dependsOn(tasks.named("sourceWithCommon"))
}
tasks.named('remapJar') {
    destinationDirectory.set(file("../builds/jar")) // 输出到 build/customLibs
    archiveFileName.set("${rootProject.mod_name}-Fabric-${rootProject.minecraft_version}-${rootProject.version}.jar")
}
//tasks.register("remapYarnJar", RemapJarTask) {
//    dependsOn tasks.jar
//
//    inputFile.set(tasks.named("jar").flatMap { it.archiveFile })
//
//    destinationDirectory.set(file("../builds/jar"))
//    archiveFileName.set(
//            "${rootProject.mod_name}-Fabric-Yarn-${rootProject.minecraft_version}-${rootProject.version}.jar"
//    )
//
//    targetNamespace.set("named") // Yarn
//}
fabricApi {
    configureDataGeneration {
        client = true
        modId = "cooparticlesapi"
    }
}
def properties = new Properties()
def repoFile = rootProject.file("repo.properties")
if (repoFile.exists()) {
    repoFile.withInputStream { properties.load(it) }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = rootProject.group
            artifactId = "${rootProject.artifact}-fabric"
            version = "${rootProject.version}"
            artifact(tasks.named("remapJar"))
            artifact(tasks.named("sourceWithCommon")) {
                classifier = "sources"
            }
        }
    }

    repositories {
        maven {
            name = "repo"
            url = uri("https://nexus.jsdu.cn/repository/maven-releases/")
            credentials {
                username = properties.getProperty("repo.user") ?: ""
                password = properties.getProperty("repo.password") ?: ""
            }
        }
    }
}
loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}