plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}
tasks.javadoc {
    // fuck javadoc encode error
    enabled = false
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.register("sourceWithCommon", Jar) {
    def current = tasks.named("sourcesJar").get()
    dependsOn(current)
    from current.outputs.files.collect { zipTree(it) }
    def other = project(":common").tasks.named("sourcesJar")
    dependsOn(other)
    from zipTree(other.get().archiveFile)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//    exclude "META-INT/**"
    destinationDirectory.set(file("../builds/sources"))
    archiveFileName = "${rootProject.mod_name}-NeoForge-Source-${rootProject.version}.jar"
}
tasks.named('jar', Jar) {
    destinationDirectory.set(file("../builds/jar")) // 输出到 build/customLibs
    archiveFileName.set("${rootProject.mod_name}-NeoForge-${rootProject.minecraft_version}-${rootProject.version}.jar")
    dependsOn(tasks.named("sourceWithCommon"))
}
def properties = new Properties()
def repoFile = rootProject.file("repo.properties")
if (repoFile.exists()) {
    repoFile.withInputStream { properties.load(it) }
}
repositories {
    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }
    maven {
        url = uri("https://maven.su5ed.dev/releases")
        content {
            includeGroup("org.sinytra.forgified-fabric-api")
        }
    }
    maven {
        name = "Kotlin for Forge"
        setUrl("https://thedarkcolour.github.io/KotlinForForge/")
    }
    maven {
        name = "jsdu-snapshot"
        url = "https://nexus.jsdu.cn/snapshots"
        mavenContent {
            snapshotsOnly()
        }
    }

    maven {
        name = "jsdu"
        url = "https://nexus.jsdu.cn/repository"
    }
    flatDir {
        dirs "../depend"
    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = rootProject.group.toString()
            artifactId = "${rootProject.artifact}-neoforge"
            version = rootProject.version.toString()

            artifact(tasks.named("jar"))
            artifact(tasks.named("sourceWithCommon")) {
                classifier = "sources"
            }
        }
    }

    repositories {
        maven {
            name = "repo"

            def isSnapshot = rootProject.version.toString().endsWith("SNAPSHOT")

            url = uri(
                    isSnapshot
                            ? "https://nexus.jsdu.cn/snapshots"
                            : "https://nexus.jsdu.cn/repository"
            )

            credentials {
                username = properties.getProperty("repo.user") ?: ""
                password = properties.getProperty("repo.password") ?: ""
            }
        }
    }
}

dependencies {
    compileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])
    compileOnly "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"
    compileOnly "org.sinytra.forgified-fabric-api:fabric-renderer-api-v1:3.4.0+9c40919e19"
    implementation "thedarkcolour:kotlinforforge-neoforge:5.10.0"
    jarJar(implementation "com.ezylang:EvalEx:3.5.0")
    jarJar(implementation 'io.github.classgraph:classgraph:4.8.184')
    additionalRuntimeClasspath fileTree(dir: "../depend", includes: ["*.jar"])
    additionalRuntimeClasspath 'io.github.classgraph:classgraph:4.8.184'
}
sourceSets.main.resources {
    srcDir 'src/generated/resources'
    srcDir '../fabric/src/main/generated/'
    exclude '**/.cache/**' // 排除 cache 文件夹
}
