package cn.coostack.cooparticlesapi.renderer.shader

import org.lwjgl.opengl.GL33

enum class GlBufferUsage(val gl: Int) {
    GL_STATIC_DRAW(GL33.GL_STATIC_DRAW),
    GL_STATIC_READ(GL33.GL_STATIC_READ),
    GL_STATIC_COPY(GL33.GL_STATIC_COPY),
    GL_DYNAMIC_READ(GL33.GL_DYNAMIC_READ),
    GL_DYNAMIC_COPY(GL33.GL_DYNAMIC_COPY),
    GL_DYNAMIC_DRAW(GL33.GL_DYNAMIC_DRAW),
    GL_STREAM_DRAW(GL33.GL_STREAM_DRAW),
    GL_STREAM_READ(GL33.GL_STREAM_READ),
    GL_STREAM_COPY(GL33.GL_STREAM_COPY),
}